---
- name: Use create_file role
  hosts: localhost
  roles:
    - role: my_own_namespace.yandex_cloud_elk.create_file
      vars:
        file_path: "/tmp/from_role.txt"
        file_content: "test module from role"
